version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GOOGLE_MAP_API_KEY=<your_google_map_api_key>
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - MONGODB_URI=<your_mongodb_uri>
